# Generated by Django 2.0.9 on 2018-10-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_password',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
