# Generated by Django 2.0.9 on 2018-10-22 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_users_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_phone',
        ),
    ]
