# Generated by Django 2.0.9 on 2018-10-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20181022_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_no',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
