# Generated by Django 2.0.9 on 2018-10-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_users_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='verify_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='verify_user',
            name='phone_no',
            field=models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='notification.Users'),
        ),
    ]
